# Generated by Django 4.0.1 on 2022-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cardinfo_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
