# Generated by Django 4.0.1 on 2022-01-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usercode_score_delete_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='name',
            field=models.CharField(default='code.py', max_length=128),
            preserve_default=False,
        ),
    ]
