# Generated by Django 4.0.1 on 2022-01-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_login_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        ),
    ]
