# Generated by Django 4.0.1 on 2022-01-11 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_link', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            managers=[
                ('random_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='code_link',
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.user'),
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('score', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='userrating',
            name='code_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.usercode'),
        ),
    ]
