# Generated by Django 4.0.1 on 2022-01-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cardinfo_remove_userrating_code_link_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cardinfo',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='userrating',
            old_name='rating',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='usercode',
            name='score',
        ),
    ]
